### ISSUE TITLE
Update Aquatic saves do not process

### ISSUE THREAD

**Issue by jeffmeden** [Plethora777/mcpe_viz#57] opened 2018-05-19 01:46 UTC
Saves with the latest Win 10 build (i.e. first Update Aquatic or 1.4.0) fail due to invalid tag types

> mcpe_viz v0.0.37 by Plethora777
> Reading XML from ./mcpe_viz.xml
> Reading config from ./mcpe_viz.cfg
> parseLevelFile: name=worlds\pxgDAPIwKwA=/level.dat version=8 len=1661
>   Found World Spawn: x=960 y=32767 z=4
>   Level name is [grand experiment]
> DB Open: dir=worlds\pxgDAPIwKwA=
> DB Open Status: OK (block_size=4096 bloom_filter_bits=10)
> Scan keys to get world boundaries
>   Bounds (chunk): DimId=0 X=(0 111) Z=(-47 56)
>   Bounds (pixel): DimId=0 X=(0 1776) Z=(-752 896) Image=(1792 1664)
>   Bounds (chunk): DimId=1 X=(0 0) Z=(0 0)
>   Bounds (pixel): DimId=1 X=(0 0) Z=(0 0) Image=(16 16)
>   Bounds (chunk): DimId=2 X=(0 0) Z=(0 0)
>   Bounds (pixel): DimId=2 X=(0 0) Z=(0 0) Image=(16 16)
>   9665 records
> Active 'hide-top', 'force-top', and 'geojson-block':
>   'geojson' block: overworld - End Portal Frame (dimId=0 blockId=120 (0x78))
>   'hide-top' block: nether - Bedrock (dimId=1 blockId=7 (0x07))
>   'hide-top' block: nether - Netherrack (dimId=1 blockId=87 (0x57))
>   'hide-top' block: nether - Lava (dimId=1 blockId=10 (0x0a))
>   'hide-top' block: nether - Stationary Lava (dimId=1 blockId=11 (0x0b))
> Parse all leveldb records
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 34) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 66) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 66) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 34) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 24) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 112) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 35) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 33) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 24) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 43) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 20) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 20) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 14) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 34) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
> NBT exception: (Invalid tag type: 0) (eof=false) (is=false)

**Comment by jeffmeden** [comment] 2018-05-19 15:42
Another note, it seems that saves not in experimental mode do process, but with chunk corruption in the image.  Saves in experimental mode fail before generating any output besides the master txt file.

**Comment by Plethora777** [comment] 2018-05-19 16:29
Oh boy.  Another change eh?  I'll have a look.

**Comment by Grimtoc** [comment] 2018-05-23 16:31
Plethora777, this is Grimtoc from reddit that sent you a PM there.  This is what was happening to me as well.  I'll create a new issue as we are NOT in experimental and it still fails to process, but the issue appears the same:
mcpe_viz v0.0.37 by Plethora777
Reading XML from C:\Users\jbland\Desktop\MCPE VIZ 64/mcpe_viz.xml
Reading config from C:\Users\jbland\Desktop\MCPE VIZ 64/mcpe_viz.cfg
parseLevelFile: name=C:/Users/jbland/OneDrive/Minecraft Share/MPECANrTBAA=/level.dat version=8 len=1853
  Found World Spawn: x=16 y=32767 z=4
  Level name is [Anavrin - Copy]
DB Open: dir=C:/Users/jbland/OneDrive/Minecraft Share/MPECANrTBAA=
DB Open Status: OK (block_size=4096 bloom_filter_bits=10)
Scan keys to get world boundaries
  Bounds (chunk): DimId=0 X=(-317 374) Z=(-286 315)
  Bounds (pixel): DimId=0 X=(-5072 5984) Z=(-4576 5040) Image=(11072 9632)
  Bounds (chunk): DimId=1 X=(-26 38) Z=(-34 27)
  Bounds (pixel): DimId=1 X=(-416 608) Z=(-544 432) Image=(1040 992)
  Bounds (chunk): DimId=2 X=(0 0) Z=(0 0)
  Bounds (pixel): DimId=2 X=(0 0) Z=(0 0) Image=(16 16)
  1593137 records
Active 'hide-top', 'force-top', and 'geojson-block':
  'geojson' block: overworld - End Portal Frame (dimId=0 blockId=120 (0x78))
  'hide-top' block: nether - Bedrock (dimId=1 blockId=7 (0x07))
  'hide-top' block: nether - Netherrack (dimId=1 blockId=87 (0x57))
  'hide-top' block: nether - Lava (dimId=1 blockId=10 (0x0a))
  'hide-top' block: nether - Stationary Lava (dimId=1 blockId=11 (0x0b))
Parse all leveldb records
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 34) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 82) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 114) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 136) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 26) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
  Processing records: 10000 / 1593137 (0.6%)
NBT exception: (Invalid tag type: 130) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 16) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 54) (eof=false) (is=false)
NBT exception: (Invalid tag type: 98) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 12) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 85) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 119) (eof=false) (is=false)
NBT exception: (Invalid tag type: 112) (eof=false) (is=false)
NBT exception: (Invalid tag type: 112) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 85) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 33) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 45) (eof=false) (is=false)
NBT exception: (Invalid tag type: 64) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 14) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 51) (eof=false) (is=false)
NBT exception: (Invalid tag type: 33) (eof=false) (is=false)
NBT exception: (Invalid tag type: 34) (eof=false) (is=false)
NBT exception: (Invalid tag type: 57) (eof=false) (is=false)
NBT exception: (Invalid tag type: 12) (eof=false) (is=false)
NBT exception: (Invalid tag type: 48) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 26) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 28) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 16) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 24) (eof=false) (is=false)
NBT exception: (Invalid tag type: 102) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 170) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
  Processing records: 20000 / 1593137 (1.3%)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 136) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 33) (eof=false) (is=false)
NBT exception: (Invalid tag type: 224) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 221) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 119) (eof=false) (is=false)
NBT exception: (Invalid tag type: 80) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 85) (eof=false) (is=false)
NBT exception: (Invalid tag type: 16) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 148) (eof=false) (is=false)
NBT exception: (Invalid tag type: 33) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 34) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 187) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 85) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 102) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 16) (eof=false) (is=false)
NBT exception: (Invalid tag type: 85) (eof=false) (is=false)
NBT exception: (Invalid tag type: 34) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 85) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 34) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 33) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 20) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
  Processing records: 30000 / 1593137 (1.9%)

Then it crashes, both in helper and command line.

Thanks again!

**Comment by Plethora777** [comment] 2018-05-23 17:05
Just pushed an update which should fix this.  It's a bit hacky though as it does not address the new separate storage for water overlay.  Gotta think about that for a bit.  Let me know how things go for you.

**Comment by willfitzpatrick** [comment] 2018-11-12 15:44
Hi @Plethora777 -
Thank you for this amazing tool.
I've recently encountered issues with the application crashing out "MCPE Viz failed." in both win32 and win64.
I've had no issues for months with the win64 version, all post aquatic update.  The last three lines from the progress log are below.
The issue is happening on all recent downloads of the world.
If I run the app on an old download, there are no issues.

The only thing that stands out to me is that this started happening after I added in Soul Sand Bubble Columns.

```
WARNING: getBlockByUname failed to find uname=minecraft:seagrass
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
WARNING: getBlockByUname failed to find uname=minecraft:bubble_column
```

Any input you might have would be immensely appreciated.

Cheers,

Will
[Will's Realm - Copy.txt](https://github.com/Plethora777/mcpe_viz/files/2572529/Will.s.Realm.-.Copy.txt)

**Comment by jeffmeden** [comment] 2018-12-24 12:53
Fantastic!  Works with 1.8.0 +experimental.  It gave a weird dump of warnings for wooden stair types during Do Output, but generation was flawless.  Also fixed an issue i saw where "minecart with chest" was always hidden from output.

`WARNING: Did not find block variant for block(Stairs, Jungle Wood) with blockdata=13 (0xd) MSG3
WARNING: Did not find block variant for block(Stairs, Birch Wood) with blockdata=12 (0xc) MSG3
WARNING: Did not find block variant for block(Stairs, Jungle Wood) with blockdata=9 (0x9) MSG3
WARNING: Did not find block variant for block(Stairs, Spruce Wood) with blockdata=9 (0x9) MSG3`

**Comment by Plethora777** [comment] 2018-12-24 15:51
@jeffmeden Yep that'll happen for a bit until we fill in the XML file with some of those missing items.  I'll make an update that reduces the volume of messages though

**Comment by willfitzpatrick** [comment] 2018-12-24 16:07
Hi @Plethora777  - I'm back in business.  Thank you very much, let me know if there is a way I could buy you a coffee, or any other beverage!

**Comment by Plethora777** [comment] 2018-12-24 17:11
@willfitzpatrick glad to hear it! -- as for thanks, do something nice for someone :)

**Comment by Plethora777** [comment] 2018-12-28 16:13
I think this may be fixed by the new versions lately.  I'm going to close this.  Please feel free to open a new one if it's still a problem.

**Closed by Plethora777** 2018-12-28 16:13 UTC
