### ISSUE TITLE
Images corrupted

### ISSUE THREAD

**Issue by phunni** [Plethora777/mcpe_viz#56] opened 2018-03-08 22:01 UTC
Newly created world is impossible to view and most cells are either called "Unknown RGB" or are listed as something extremely unlikely in that place (as I say, brand new world).

I suspect it's due to an incompatibility with the latest beta version.

![download](https://user-images.githubusercontent.com/11048658/37178994-18304724-231c-11e8-8735-72ab3fc49186.png)

**Comment by phunni** [comment] 2018-03-09 16:48
I noticed in the final point of the Changes list [here](https://minecraft.gamepedia.com/Bedrock_Edition_1.2.13) that they no longer use Block IDs.  Could this be the cause of this bug?  would it also mean that mcpe_)viz won't work anymore?  I'm really hoping not since I use mcpe_viz extensively with my worlds...

**Comment by Plethora777** [comment] 2018-03-19 19:20
I'm on the case.  It's a fun & maddening investigation.... Mojang did some deep weirdness to save storage space for worlds... Back to it.  I'll update when I've got it solved.

**Comment by phunni** [comment] 2018-03-19 20:55
Cool - thanks.  As I said, I'm really hoping the changes they've made haven't broken mcpe_viz. I'm so used to using it's hard to imagine Minecraft without it!

**Comment by vvanhee** [comment] 2018-04-05 16:31
You may have already seen this, but if not, it is a description of changes in how blocks are represented in Bedrock now: https://gist.github.com/Tomcc/a96af509e275b1af483b25c543cfbf37

**Comment by Plethora777** [comment] 2018-04-05 19:25
@vvanhee thanks very much for that link.  I'd already updated the code to deal with *most* of the new chunk record stuff.  The info in that link should help with the rest (packed bit madness!)

**Comment by Plethora777** [comment] 2018-04-05 19:28
@Thunder33345 sort of agree, the stuff they are doing.... seems strange.  Like writing code for an early computer with 4k of storage strange... It's very flexible but also sort of insane.  I don't see the clear benefit of this packed bit business.  I guess it saves space, but the cost in, well, sanity is high.  And the space savings are lost as soon as you have a sub-chunk with a high number of diff blocks.

**Comment by Plethora777** [comment] 2018-04-09 15:59
Just pushed an update - give it a try.  Please note that --spawnable no longer works because the new paletted chunk format does not store block light info.  (This is too bad)

**Comment by phunni** [comment] 2018-04-09 16:07
Cool, will hopefully be able to give it a try this evening.

**Comment by vvanhee** [comment] 2018-04-09 18:59
Wow, that was quick!  Fantastic! Will try it tonight.

**Comment by phunni** [comment] 2018-04-09 19:17
Just ran it and it seems to have worked, although I get a lot of:

> WARNING: getBlockByUname failed to find uname=minecraft:hardened_clay

That's the only one I get now. I was getting loads of different ones before I copied the mcpe_viz.xml.  Has the config changed much/at all? I haven't copied it over my existing one, so I'm assuming not since it works.

**Comment by Plethora777** [comment] 2018-04-09 19:33
@phunni Yep there will be loads of those until we have it covered in the XML file.  I added "uname=" for blocks.  I'll need to add support for aliases as there seems to be some inconsistencies.  I just wanted to get an update out that worked first :)  Need to think about how to handle the diff unames

**Comment by vvanhee** [comment] 2018-04-10 00:49
So far it’s looking great! I ran into a strange issue only on level 15
where it’s showing large areas of bedrock — anyone else seeing this?

**Comment by vvanhee** [comment] 2018-04-10 10:25
I can reproduce the problem with bedrock on level 15 using a new map, then every 16th layer has odd issues — starting at level 14 and hitting the up arrow should demonstrate the issue. Layers 31, 47, 63, 79, and 95 seem off compared to layers above and below, with odd pixels of air at regular intervals or other issues. Then going way up, I don’t get 100% air as I think I should, with the top solid blocks not getting erased. I should probably open a new ticket. Thanks!

**Comment by Plethora777** [comment] 2018-04-14 15:30
@vvanhee Just pushed an update for that issue - thanks for pointing it out

**Comment by vvanhee** [comment] 2018-04-17 05:00
Great!

**Comment by Plethora777** [comment] 2018-12-28 16:14
I think this may be fixed by the new versions lately.  I'm going to close this.  Please feel free to open a new one if it's still a problem.

**Closed by Plethora777** 2018-12-28 16:14 UTC
